### ISSUE TITLE
goldchain crashes on startup on latest master

### ISSUE THREAD

**Issue by LeeSmet** [nbh-digital/goldchain#57]
output:

```
.-(~/goldchain)---------------------------------------------------------------------------------------------(lee@kopi)-
`--> goldchaind --network testnet -M cgte  
panic: invalid version: apha-3.0-664b70a

goroutine 1 [running]:
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/build.MustParse(...)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/build/version.go:51
github.com/nbh-digital/goldchain/pkg/config.init.0()
	/home/lee/go/src/github.com/nbh-digital/goldchain/pkg/config/config.go:215 +0xa0
```

**Comment by LeeSmet** [comment]
Issue is caused by a wrongly formatted tag. When building with the makefile, the version is injected, which is taken (in part) from git describe (meaning the latest tag). On daemon startup, the version string is parsed. The code expects the tag part of the version to be semver compliant, i.e. `v0.3.0`

**Comment by LeeSmet** [comment]
Removed offending tag and created a new tag with the proper format at the tagged commit. After rebuilding goldchaind runs fine again.

**Comment by LeeSmet** [comment]
Anyone who already pulled the tag will still have it in the tag list, but the new tag will override it in the version injection
