### ISSUE TITLE
Some transactions cause blockcreators to crash

### ISSUE THREAD

**Issue by LeeSmet** [nbh-digital/goldchain#62]
Eventually these transactions are marked as invalid (probably due to custody fees)

**Comment by LeeSmet** [comment]
Loading...
Binding API Address and serving the API...
Setting up root HTTP API handler...
Loading gateway (1/5)...
Loading consensus set (2/5)...
Loading transaction pool (3/5)...
Loading wallet (4/5)...
Loading block creator (5/5)...
Finished loading in 0.072060613 seconds
Rescanning consensus set...

Done!
goroutine 26 [running]:
runtime/debug.Stack(0x449487, 0x0, 0xc00023fc80)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/build.Critical(0xc00023fe60, 0x2, 0x2)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/build/critical.go:15 +0xaa
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/persist.(*Logger).Critical(0xc0003e8fc0, 0xc00023fe60, 0x2, 0x2)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/persist/log.go:39 +0xcc
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc0003f2000, 0x607ae5fe78011926, 0xeebdccdd133aa0ef, 0xa65a832b6160f782, 0x609bb04688136029, 0x5da095d0, 0x313, 0x0, 0x0, 0xc0003b45f0, ...)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator/blockmanager.go:32 +0x1ea
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc0003f2000)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator/proofofblockstake.go:49 +0x27d
created by github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator.New
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator/blockcreator.go:142 +0x5bb
Critical error: ERROR: an invalid block was submitted: spent coin output 96d5dc62b3b9d49105016e7324ce224245542148ce3c9e6f0ea2b4a465f535d2 is created in the future (1570805200) compared to given computation time 1570804860
Please submit a bug report here: https://github.com/threefoldtech/rivine/issues
panic: Critical error: ERROR: an invalid block was submitted: spent coin output 96d5dc62b3b9d49105016e7324ce224245542148ce3c9e6f0ea2b4a465f535d2 is created in the future (1570805200) compared to given computation time 1570804860
Please submit a bug report here: https://github.com/threefoldtech/rivine/issues


goroutine 26 [running]:
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/build.Critical(0xc00023fe60, 0x2, 0x2)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/build/critical.go:17 +0x136
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/persist.(*Logger).Critical(0xc0003e8fc0, 0xc00023fe60, 0x2, 0x2)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/persist/log.go:39 +0xcc
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc0003f2000, 0x607ae5fe78011926, 0xeebdccdd133aa0ef, 0xa65a832b6160f782, 0x609bb04688136029, 0x5da095d0, 0x313, 0x0, 0x0, 0xc0003b45f0, ...)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator/blockmanager.go:32 +0x1ea
github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc0003f2000)
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator/proofofblockstake.go:49 +0x27d
created by github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator.New
	/home/lee/go/src/github.com/nbh-digital/goldchain/vendor/github.com/threefoldtech/rivine/modules/blockcreator/blockcreator.go:142 +0x5bb
